### ISSUE TITLE
Code is not licensed

### ISSUE THREAD

**Issue by z93blom** [encse/adventofcode-2017#1]
Loving this repo - it provides a very good starting point for solving the advent of code problems, but the code doesn't have a license associated with it, which means that it cannot really be used by me (or someone else) to provide our own solutions.

Is it possible to add a license to the repository?
See https://help.github.com/en/articles/licensing-a-repository for more information about licenses.

**Comment by encse** [comment]
Hey @z93blom. Thanks for pointing out. Just added the MIT license.
