### ISSUE TITLE
2022 Day 21

### ISSUE THREAD

**Issue by erik-linthorst** [encse/adventofcode-2017#10]
Hi David,

There seems to be an issue with the solution for Monkey Math (2022/21 ).  The local function buildExpr within the Parse function, complains about 'name not found'. This happens when the name is looked up the context dictionary, while building the expression tree (before simplify is called).

This happens both with file included in the repo as well as with my personal input file.  In repo file complains about 'rcmw'. In my personal file this is 'jwcp'.

I have observed that both are a defined by a sum operation and are used once, as input to a multiplication operation. The name/sum operation is part of the dictionary before it builds the expression tree.

I would have loved to contribute via a PR, but I cannot seem to find the issue.

My compliments for your very smart and elegant solutions. They have inspired me to make my code better. tipped me about how to get the puzzle solved. And last few days, simply to produce my answer, when I I was not able to solve it. Thank you!

Kind regards,
Erik Linthorst
Amsterdam, The Netherlands

[aoc-y2022-d21-erik.txt](https://github.com/encse/adventofcode/files/10284599/aoc-y2022-d21-erik.txt)

![with-repo-input-file](https://user-images.githubusercontent.com/1905738/209077165-710a5c12-960a-4d01-a046-276fa64b080f.png)

![with-eriks-input-file](https://user-images.githubusercontent.com/1905738/209077170-d41d66d6-efa5-4bab-9ddf-70043dada87b.png)

![jwcp-occurrances-in-eriks-input-file](https://user-images.githubusercontent.com/1905738/209080976-3a3f5f0d-9edc-47f0-a9e3-2df751306296.png)

![rcmw-occurrances-in-repo-input-file](https://user-images.githubusercontent.com/1905738/209080979-95f864b8-1afb-45c1-b3ae-cc03113ad837.png)

**Comment by encse** [comment]
Interesting 🤔 i’ll look into it. It has definitely worked on my machine.

**Comment by erik-linthorst** [comment]
Looking in all the wrong places, Just now I notice, working on a windows machine while you are on a linux machine.  I should be splitting on /r/n. Sorry for the fuzz.

**Comment by encse** [comment]
Ok then! I don't know what would be the best way to deal with it. I could use Environment.NewLine everywhere, but that would be too much characters. Or I could normalize the input so that it's always has just `\n`-s.

**Comment by encse** [comment]
@erik-linthorst, FYI: I just changed the normalizer function to remove the "\r" from the input.

https://github.com/encse/adventofcode/blob/master/Lib/Runner.cs#L86-L87

**Comment by erik-linthorst** [comment]
Brilliant, thank you!
