### ISSUE TITLE
2023-day23-part2: error with my input

### ISSUE THREAD

**Issue by erik-linthorst** [encse/adventofcode-2017#14]
Hi David, 

I am totally stuck with part 2 of day 24. Your solution trips on line 111.  I don't know if it's due to my input file, 

I cannot seem to get a valid result from cameronaavik or penguin solutions either.  See: https://github.com/Bogdanp/awesome-advent-of-code?tab=readme-ov-file#c-1 They are the only other C# solutions to day 24 part2 that I could find.

I have attached my input file. 

I find it very frustrating not being able to get the final star. So if ever you feel like having a look, it would make me very happy if you could spot the issue.

Kind regards.
Erik

**Comment by encse** [comment]
@erik-linthorst  are you 200% sure that this is the right input? the other two solutions use linear algebra, mine uses chinese remainder theorem. if none of these work, I think you input is flawed.

**Comment by erik-linthorst** [comment]
Just double checked again, but this really is the input that is provided. All solutions solve part one just fine. 

The solution of Cameron throws an error error too. Penguin produces a result, but it is not accepted/too low. Thanks for having a look.

**Comment by encse** [comment]
@erik-linthorst I just found something. Can you try it now with this? 948485822969419

**Comment by erik-linthorst** [comment]
YEAH! that was it! 

Seeing the the changes, 'found something' seems like an understatement. I am very happy I can close close this puzzle. Would not have solved that one in a million years.  Thank you very much for your help and insights. Best of wishes for the new year.

**Comment by encse** [comment]
@erik-linthorst I'm working on the write up, hope that it will make sense. 

Happy new year!
