### ISSUE TITLE
Recommend deleting inputs, per request from AoC Author

### ISSUE THREAD

**Issue by viceroypenguin** [encse/adventofcode-2017#15]
https://x.com/ericwastl/status/1465805354214830081

**Comment by encse** [comment]
Did you find an input somewhere?

**Comment by viceroypenguin** [comment]
I saw a bunch of input.in files. Are those not inputs?

**Comment by encse** [comment]
Those are supposed to be all encrypted. I dont think there is anything checked in as plain text

**Comment by viceroypenguin** [comment]
Ah, ok. I didn't read them. Sorry! :)

**Comment by encse** [comment]
Ok cool

**Comment by xcom169** [comment]
How to put my own inputs into the folders? Shall I encrypt them?

**Comment by encse** [comment]
@xcom169 start from my template repo, it has detailed instructions.

**Comment by xcom169** [comment]
For Windows it doesnt tell what to do. Is it a must to encrypt my input
files?

**Comment by encse** [comment]
@xcom169 you should not make your input available for others. You can setup gitcrypt on windows, i just dont have a windows around to figure it out. Alternatively: you can also add the input files to tgitignore or make your repo private. Personally, i would try to setup gitcrypt on windows.

**Comment by xcom169** [comment]
Okay, thanks

**Comment by xcom169** [comment]
Which IDE you were using during development for git-crypt?

**Comment by encse** [comment]
I’m on a mac, I use vscode
