### ISSUE TITLE
Day 7 - accumulator

### ISSUE THREAD

**Issue by bulatgrzegorz** [encse/adventofcode-2017#16]
In filter method, value 0 is being passed to check delegate as accumulator value. This will cause inccorect behaviour in some specific situations, like:

6: 7 3 2

This one obviously has no solutions, but with accumulator 0, we can put on operations: *, ||, *, which in steps will result with 0, 3 (03), 6.

Btw. I really like your solutions

**Comment by encse** [comment]
Good catch!

**Comment by encse** [comment]
Fixed thanks. This has also  improved the runtime by about 50%
