### ISSUE TITLE
There is a little offset issue

### ISSUE THREAD

**Issue by Lorilatschki** [encse/adventofcode-2017#17]
https://github.com/encse/adventofcode/blob/0e9dee74f8e41a2f50fe2fa702869d3b187b3c8c/2024/Day22/Solution.cs#L35

There is a little offset issue IMHO. This way it would work. By the way, i love your expresive style, it's awesome!

```dotnet
for (var i = 0; i <= bananasSold.Length - 5; i++)
{
    var slice = bananasSold[i..(i + 5)];
    var seq = string.Join(",", Diff(slice));
    if (!buyOptions.ContainsKey(seq))
    {
        buyOptions[seq] = slice.Last();
    }
}
```

**Comment by encse** [comment]
That's right. Thanks. Fixed.
