### ISSUE TITLE
Bring back the 'test' feature

### ISSUE THREAD

**Issue by encse** [encse/adventofcode-2017#5]
I got it removed, because I never used it, but I see that @FaustVX started to use it, so I'll add it back.
Things are not that simple if you have a user...

**Comment by FaustVX** [comment]
Ok, thanks,
Yes I use it. But on my own branch, I changed the order (test dir, then working dir)

Also, when there is only 1 test file, the file name isn't printed.
I still didn't worked on it, but I will create a Pull Request when I'll look at it.

And yes, thinking for others is complicated :)
